SHARED: &SHARED
  store: example.myshopify.com
  password: test
  theme_id: 'live'
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "*.swp"
    - "*~"
    - "config/settings_data.json"

development:
  <<: *SHARED
  password: ADD_PASSWORD_HERE
  store: TEST_STORE_NAME.myshopify.com

production:
  <<: *SHARED
  password: ADD_PASSWORD_HERE
  store: LIVE_STORE_NAME.myshopify.com